### ISSUE TITLE
Concurrency issue in templateengine

### ISSUE THREAD

**Issue by sbomer** [dotnet/templating#1355]
I'm running some integration tests that try to call `dotnet new`. When I execute them one at a time, they always succeed, but when I run them concurrently, I frequently get the following stack trace:

```
Error reading JObject from JsonReader. Path '', line 0, position 0.
    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
    at Newtonsoft.Json.Linq.JObject.Parse(String json)
    at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.EnsureTemplatesLoaded()
    at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.WriteTemplateCache(IList`1 templates, String locale)
    at Microsoft.TemplateEngine.Edge.Settings.TemplateCache.WriteTemplateCacheForLocale(String locale, String existingCacheVersion)
    at Microsoft.TemplateEngine.Edge.Settings.TemplateCache.WriteTemplateCaches(String existingCacheVersion)
    at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save(TemplateCache cacheToSave)
    at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save()
    at Microsoft.TemplateEngine.Edge.Settings.ComponentManager.Register(Type type)
    at Microsoft.TemplateEngine.Edge.Settings.ComponentManager..ctor(ISettingsLoader loader, SettingsStore userSettings)
    at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.EnsureLoaded()
    at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.RebuildCacheFromSettingsIfNotCurrent(Boolean forceRebuild)
    at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__59.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
    at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()
```

This seems to be caused by the template engine trying to write the template cache simultaneously from different processes.

The error looks similar to the one reported in https://github.com/dotnet/templating/issues/1319, but the suggested fix (reinitializing the cache) doesn't fix the underlying problem.

**Comment by seancpeters** [comment]
@sbomer - Based on that stack trace, you're most likely correct that the cache is being written simultaneously by multiple processes, which leads to this type of error / and can cause cache corruption in general. To avoid this problem while running simultaneous tests, you could use the recently implemented flag `--debug:custom-have` (disclaimer: the 'debug' flags are not technically supported or guaranteed to remain the same, or even exist in future versions - but probably won't change). This flag requires exactly one argument, the path to where you want the custom hive to be located (or is already located). If a hive already exists at the specified location, it will be used. If no hive exists there, one will be created in the same way as the default hive is created when first running dotnet net. 
 
This flag can be added to any command, so for unit tests, each test could use a different custom hive path, and then there would be no clashes writing the cache, since each test is writing to a different location on the file system (assuming unique paths were chosen) for each test. You'd just need to add `--debug:custom-hive <path to hive for this test>` to each of the test commands. 

The hives created by using this flag are persistent - there's nothing built-in that causes them to be deleted. So you'd probably want some sort of cleanup code in your tests that deletes their respective hives. You could also have the first command in each test also include the flag `--debug:reinit` in case there was already a hive at the specified custom, then the hive would be reinitialized to the initial state. This could be important if a previous test run failed to delete the hives it created.

**Comment by mlorbetske** [comment]
@seancpeters has submitted a PR for this https://github.com/dotnet/templating/pull/1360
