### ISSUE TITLE
System.FormatException: Input string was not in a correct format. while using string.Format with local function in netcoreapp2.0+netstandard2.0

### ISSUE THREAD

**Issue by Frank591** [dotnet/templating#1632]
**About my machine:**
dotnet --version = 2.1.302
TargetFramework = netcoreapp2.0 for main service and 
netstandard2.0 for dependency library with problem code
С# lang version = 7.1

**Steps:**
1) Object description
```
 [DataContract]
    public class ErrorResponse
    {
        public ErrorResponse([CanBeNull] string problemDescription  )
        {
            ProblemDescription = problemDescription;
        }
  

        [CanBeNull]
        [DataMember]
        public string ProblemDescription { get; }

    }
```
2) create ErrorResponse object with ProblemDescription 
`Error converting value {null} to type 'System.Decimal'. Path 'products[0].taxPercent', line 1, position 366.`

**Current:**
`string.Format("Error message:{0}. ", errorResponse.ProblemDescription)` 
works ok
`string.Format($"Error message:{errorResponse.ProblemDescription}")`
throws error
```
System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)

```
**Expected:**
`string.Format($"Error message:{errorResponse.ProblemDescription}")` 
has same output with
`string.Format("Error message:{0}. ", errorResponse.ProblemDescription)`

**Comment by Frank591** [comment]
Sorry. My bad. Incorrect use of local function inside string.Format. Please remove this issue.
