### ISSUE TITLE
Object reference not set to an instance of an object. Dot net Vue

### ISSUE THREAD

**Issue by originAsad** [dotnet/templating#1803]
I am Working on creating a Boiler Plate with Asp.net Core with Vue.js 
I am creating a new Project but i am getting these Errors
```
[ASP.NET Core with Vue.js 2 (C#)
Author: Mark Pieszak, Mladen Mihajlovic
Object reference not set to an instance of an object.
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.TemplateUsageHelp.GetTemplateUsageInformation(ITemplateInfo templateInfo, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.TemplateDetailsDisplay.DetermineParameterDispositionsForTemplateGroup(IReadOnlyList`1 templateGroup, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.TemplateDetailsDisplay.ShowTemplateGroupHelp(IReadOnlyList`1 templateGroup, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator, Boolean showImplicitlyHiddenParams)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.HelpForTemplateResolution.TemplateDetailedHelpForSingularTemplateGroup(IReadOnlyList`1 unambiguousTemplateGroup, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.HelpForTemplateResolution.DisplayHelpForUnambiguousTemplateGroup(TemplateListResolutionResult templateResolutionResult, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator, String defaultLanguage)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.HelpForTemplateResolution.CoordinateHelpAndUsageDisplay(TemplateListResolutionResult templateResolutionResult, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, ITelemetryLogger telemetryLogger, TemplateCreator templateCreator, String defaultLanguage)
   at Microsoft.TemplateEngine.Cli.New3Command.EnterTemplateManipulationFlowAsync()
   at Microsoft.TemplateEngine.Cli.New3Command.ExecuteAsync()
   at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()](url)
```

I have run this Command 

```dotnet new vuejs```

**Comment by mlorbetske** [comment]
Could you post your template.json please?

**Comment by donJoseLuis** [comment]
This issue was last touched some years ago.  We are working on a new delivery road map.  Please reopen if this is something you still want (+ your template.json) & we'll properly assess its' priority compared to other work aimed at improving the overall templating UX.
