### ISSUE TITLE
Executing dotnet new on a folder that requires elevated rights throws an exception

### ISSUE THREAD

**Issue by mairaw** [dotnet/templating#253]
I didn't realize I was trying to run the command on a folder that required elevated rights. Command should not work if I'm not running as an administrator, but I think we shouldn't be dumping the call stack.

## Steps to reproduce
Run dotnet new in a folder that you don't have write access.

## Expected  behavior
I'll get a nicely formatted error message.

## Actual behavior
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise>dotnet new console
Error while processing file /content/ConsoleApplication-CSharp/Company.ConsoleApplication1.csproj.
Check InnerException for details
Access to the path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Enterprise.csproj' is denied.
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.Create(String path)
   at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Core.Util.Orchestrator.ProcessFile(IFile sourceFile, String sourceRel, String targetDir, IGlobalRunSpec spec, IProcessor fallback, IEnumerable`1 fileGlobProcessors, IReadOnlyList`1 locOperations)

## Environment data
.NET Command Line Tools (1.0.0-rc4-004761)

Product Information:
 Version:            1.0.0-rc4-004761
 Commit SHA-1 hash:  fc475dfd51

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004761

**Comment by mlorbetske** [comment]
This has been merged, thanks!

**Comment by mlorbetske** [comment]
This has been merged, thanks!
