### ISSUE TITLE
Template "Blazor WebAssembly App" could not be created.

### ISSUE THREAD

**Issue by tomtom1992** [dotnet/templating#2772]
I have the following issue when running

dotnet new blazorwasm

or any other template:

Template "Blazor WebAssembly App" could not be created.
Error while processing file /content/ComponentsWebAssembly-CSharp/Client/App.razor
System.IO.FileNotFoundException: Could not find file 'C:\Users\Thomas\Documents\Projects\CMSTest\App.razor'.
File name: 'C:\Users\Thomas\Documents\Projects\CMSTest\App.razor'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Core.Util.Orchestrator.ProcessFile(IFile sourceFile, String sourceRel, String targetDir, IGlobalRunSpec spec, IProcessor fallback, IEnumerable`1 fileGlobProcessors, IReadOnlyList`1 locOperations)

**Comment by DavidKarlas** [comment]
This is super weird, `FileNotFoundException` is thrown while calling `System.IO.File.Create(String path)` notice this is not `DirectoryNotFoundException` or `UnauthorizedAccessException`. Which means whole path is valid, just kernel/filesystem is returning something that doesn't make much sense.

**Comment by tomtom1992** [comment]
Workaround: Not using my personal home folder, but using a folder on the C: drive directly

**Comment by tomtom1992** [comment]
Does this have anything to do with Windows 10 file access? I even ran Powershell in Admin mode, so it doesn't make much sense

**Comment by DavidKarlas** [comment]
Is your username `Thomas` or does it have some special letter?

**Comment by DavidKarlas** [comment]
Maybe you could try creating new console project and executing:
```csharp
static void Main(string[] args)
{
    var f=File.Create(@"C:\Users\Thomas\Documents\Projects\test.razor");
    f.Write(new byte[1], 0, 1);
    f.Dispose();
}
```

**Comment by vlada-shubina** [comment]
Closing the issue due to no feedback. Please do not hesitate to reopen if the issue still exists.
