### ISSUE TITLE
Object reference not set to an instance of an object for the template help for some resources.

### ISSUE THREAD

**Issue by TsuyoshiUshio** [dotnet/templating#2790]
I'm implementing the template, and found that `dotnet new TEMPLATE --help` will fails for some template. 
It works for cosmos but not for `dotnet new rqueue --help` for example.

```
dotnet new rqueue --help
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --interactive       Allows the internal dotnet restore command to stop and wait for user input or action (for example to complete authentication).
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --dry-run           Displays a summary of what would happen if the given command line were run if it would result in a template creation.
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
  --update-check      Check the currently installed template packs for updates.
  --update-apply      Check the currently installed template packs for update, and install the updates.


RabbitMQTrigger (C#)
Author: Microsoft
Object reference not set to an instance of an object.
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.FindBestHostTemplateConfigFile(IFileSystemInfo config)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.LoadTemplate(ITemplateInfo info, String baselineName)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.TemplateUsageHelp.GetTemplateUsageInformation(ITemplateInfo templateInfo, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.TemplateDetailsDisplay.DetermineParameterDispositionsForTemplateGroup(IReadOnlyList`1 templateGroup, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.TemplateDetailsDisplay.ShowTemplateGroupHelp(IReadOnlyCollection`1 templateGroup, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator, Boolean showImplicitlyHiddenParams)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.HelpForTemplateResolution.TemplateDetailedHelpForSingularTemplateGroup(IReadOnlyCollection`1 unambiguousTemplateGroup, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.HelpForTemplateResolution.DisplayHelpForUnambiguousTemplateGroup(ListOrHelpTemplateListResolutionResult templateResolutionResult, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, TemplateCreator templateCreator, ITelemetryLogger telemetryLogger, String defaultLanguage)
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.HelpForTemplateResolution.CoordinateHelpAndUsageDisplay(ListOrHelpTemplateListResolutionResult templateResolutionResult, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, ITelemetryLogger telemetryLogger, TemplateCreator templateCreator, String defaultLanguage, Boolean showUsageHelp)
   at Microsoft.TemplateEngine.Cli.New3Command.EnterTemplateManipulationFlowAsync()
   at Microsoft.TemplateEngine.Cli.New3Command.ExecuteAsync()
   at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()
```

# Reference
https://github.com/Azure/azure-functions-templates/issues/1014

https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates

**Comment by vlada-shubina** [comment]
@TsuyoshiUshio could you please add `dotnet --info` output please? 
Same template works for me in SDK 5.0.1xx, such errors usually depend on environment/install order etc. How did you install this template - from NuGet pack or from folder?

Also it would be good if you can do the [following ](https://github.com/dotnet/templating/issues/2677#issuecomment-737449060)so we get the line information, as I cannot repro it at the moment.

**Comment by TsuyoshiUshio** [comment]
There it is.   However, I might have other reason if it works in your environment. I'm developing a new template. I'd like to know 

1. From where, the `dotnet new` command find the template on my local machine? (Win 10)
2. What could missing by the stack trace I provided?  some configuration file? where to investigate it?


```
>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  3.1.405 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by vlada-shubina** [comment]
Thank you for reply.
For stack trace - I'm looking for the lines information to get exact line the exception happens.
Could you please send me json files in `<home>\.templateengine\dotnetcli\v5.0.102` to see if they are corrupted in any way? I have a suspision that path to template.json file there might be wrong.
Also if you provide the template you are referring to it would be useful, as originally I thought it happened to https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/RabbitMQTrigger-CSharp (i tried that one).
 
Some blind guesses:
- is `template.json` file in the root of your template? (e.g. not in `.template.config` folder)?
- could it be that you installed the template with the wrong folder path? (for example `azure-functions-templates\Functions.Templates\Templates\BlobTrigger-CSharp\.template.config\ instead of azure-functions-templates\Functions.Templates\Templates\BlobTrigger-CSharp). If you run `dotnet new -u` it will show you the path you used.

**Comment by TsuyoshiUshio** [comment]
Thank you @vlada-shubina

The issue has gone, probably, the root cause is that you suggested. I frequently clean up the .templatengine for avoid the old cache for testing new template.  Currently I can't repro it. I close this issue. It is good learning.
