### ISSUE TITLE
dotnet new crashes if template contains #ifdef

### ISSUE THREAD

**Issue by Larsjep** [dotnet/templating#3085]
Hi,

I'm experiencing a crash of `dotnet new` if my template contains an `#ifdef`.

Repro steps:
- unzip: [example.zip](https://github.com/dotnet/sdk/files/6325891/example.zip) 
- dotnet new -i .
- dotnet new Foo  (in a different directory)

I get this error:
```
Template "Foo" could not be created.
Error while processing file /foo.cpp
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.TemplateEngine.Core.Expressions.Cpp.CppStyleEvaluatorDefinition.Evaluate(IProcessorState processor, Int32& bufferLength, Int32& currentBufferPosition, Boolean& faulted)
   at Microsoft.TemplateEngine.Core.Operations.Conditional.Impl.HandleMatch(IProcessorState processor, Int32 bufferLength, Int32& currentBufferPosition, Int32 token, Stream target)
   at Microsoft.TemplateEngine.Core.Util.ProcessorState.Run()
   at Microsoft.TemplateEngine.Core.Util.Processor.Run(Stream source, Stream target, Int32 bufferSize, Int32 flushThreshold)
   at Microsoft.TemplateEngine.Core.Util.Processor.Run(Stream source, Stream target)
   at Microsoft.TemplateEngine.Core.Util.Orchestrator.ProcessFile(IFile sourceFile, String sourceRel, String targetDir, IGlobalRunSpec spec, IProcessor fallback, IEnumerable`1 fileGlobProcessors, IReadOnlyList`1 locOperations)

```

I have noticed the problem disappear if a 'space' is inserted after the # in the ifdef.
It also disappears if the template contains the file `bar.cpp` that contains `//-:cnd:noEmit`

I see the problem on Windows with .NET SDK (5.0.201). It doesn't appear to happen on Linux.

BR
  Lars

**Comment by DavidKarlas** [comment]
I can reproduce bug following instructions.

**Comment by DavidKarlas** [comment]
Sorry for slower response, I started looking into fixing this... Main problem here is that you are using `#ifdef` instead of `#if`...
Can you try switching to using `#if` and see if it resolves problems for you?
I'm planning to add `#ifdef` as valid condition for CPP style files, but also prevent crash like this...

**Comment by Larsjep** [comment]
Thanks for the response.
If I change it to `#if defined(foo)` it doesn't crash but the resulting foo.cpp is then just empty. And that will not work.
The workaround with the additional `<space>` after the #, like `# ifdef foo`, works fine for now, because this is allowed preprocessor syntax.

**Comment by DavidKarlas** [comment]
Oh, I misunderstood you intention, what you probably want to do is use 
```cpp
//-:cnd:noEmit
#ifdef foo
Some code
#endif
//+:cnd:noEmit
```
See [documentation](https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax#ignore-conditions-expressions-in-language-files) for more details.

**Comment by Larsjep** [comment]
Yes, reading the documentation it is clear that what I need is `//-:cnd:noEmit`
But please notice that this option apparently is preserved between files, as a `//-:cnd:noEmit` in one file seems to affect other files. (Probably because the `//+:cnd:noEmit` is missing, but then it should at least give an error)
