### ISSUE TITLE
Bug in CommandResultAssertions in dotnet-new3.IntegrationTests

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#3125]
In dotnet-new3.IntegrationTests, in case of failed custom fluent assert method index out of bound exception happens:

Error message
System.FormatException : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

Stack trace
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at FluentAssertions.Execution.MessageBuilder.FormatArgumentPlaceholders(String failureMessage, Object[] failureArgs)
   at FluentAssertions.Execution.MessageBuilder.Build(String message, Object[] messageArgs, String reason, ContextDataItems contextData, String identifier, String fallbackIdentifier)
   at FluentAssertions.Execution.AssertionScope.<>c__DisplayClass30_0.<FailWith>b__0()
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at Microsoft.NET.TestFramework.Assertions.CommandResultAssertions.HaveStdOutMatching(String pattern, RegexOptions options) in /_/test/dotnet-new3.UnitTests/Sdk/Assertions/CommandResultAssertions.cs:line 97
   at Dotnet_new3.IntegrationTests.CommonTemplatesTests.AllCommonProjectsCreateRestoreAndBuild(String expectedTemplateName, String templateShortName, String language, String framework) in /_/test/dotnet-new3.UnitTests/CommonTemplatesTests.cs:line 86

This prevents to see real reason of test failure.

**Comment by vlada-shubina** [comment]
was fixed in https://github.com/dotnet/templating/pull/3122
