### ISSUE TITLE
Including extra args dumps a call stack, doesn't provide meaningful feedback

### ISSUE THREAD

**Issue by seancpeters** [dotnet/templating#327]
Repro:
> dotnet new3 a b

Result:
```
Parameter names must start with -- or -.
   at Microsoft.TemplateEngine.Cli.AppExtensions.ParseExtraArgs(CommandLineApplication app, IList`1 extraArgFileNames)
   at Microsoft.TemplateEngine.Cli.ExtendedCommandParser.ParseArgs(IList`1 extraArgFileNames)
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.ExtendedCommandParser.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()
```

**Comment by seancpeters** [comment]
Fixed by #366

**Comment by sayedihashimi** [comment]
@seancpeters what's the new output?

**Comment by seancpeters** [comment]
Repro:
`>dotnet new3 a b`

Result: (the firt line of output is red in the console)
```
Template name is the only allowed argument. Invalid argument: [b].
Template Instantiation Commands for .NET Core CLI

Usage: dotnet new3 [arguments] [options]

Arguments:
  template  The template to instantiate.

Options:
  -l|--list         Lists templates containing the specified name. If no name is specified, lists all templates.
  -lang|--language  Specifies the language of the template to create.
  -n|--name         The name for the output being created. If no name is specified, the name of the current directory is used.
  -o|--output       Location to place the generated output.
  -h|--help         Displays help for this command.
  -all|--show-all   Shows all templates.
  --force           Forces content to be generated even if it would change existing files.

```
