### ISSUE TITLE
-x|--extra-args dumps a call stack if the args file doesn't exist

### ISSUE THREAD

**Issue by seancpeters** [dotnet/templating#329]
Repro:
`c:\temp\Creation\scratch>dotnet new3 console -x a`
Actual behavior:
```
Could not find file 'c:\temp\Creation\scratch\a'.
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.OpenRead(String path)
   at Microsoft.TemplateEngine.Cli.AppExtensions.ParseExtraArgs(CommandLineApplication app, IList`1 extraArgFileNames)
   at Microsoft.TemplateEngine.Cli.ExtendedCommandParser.ParseArgs(IList`1 extraArgFileNames)
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.ExtendedCommandParser.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()
```

**Comment by seancpeters** [comment]
fixed by #366
