### ISSUE TITLE
Unable to install template from Azure DevOps Nuget Feed

### ISSUE THREAD

**Issue by danijam** [dotnet/templating#4162]
Hi, I have my dotnet template packaged and pushed to a Azure DevOps (Cloud, not on-premises server) nuget artifact feed. I am now trying to download and install that using:

`dotnet new --install Company.Templates.SomeTemplate --nuget-source "https://pkgs.dev.azure.com/<tenantName>/<teamProjectName>/_packaging/<feedName>/nuget/v3/index.json"`

The output returned is:
```
The following template packages will be installed:
   Company.Templates.SomeTemplate

Error: Failed to read package information from NuGet source https://pkgs.dev.azure.com/<tenantName>/<teamProjectName>/_packaging/<feedName>/nuget/v3/index.json.
Warning: Company.Templates.SomeTemplate is not found in NuGet feeds https://pkgs.dev.azure.com/<tenantName>/<teamProjectName>/_packaging/<feedName>/nuget/v3/index.json, https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\.
Company.Templates.SomeTemplate could not be installed, the package does not exist.
```

I've also tried adding the `--interactive` option to the above with no difference in behaviour

My `dotnet restore` commands work successfully against this feed.

The current work around is to get users to download the nupkg to disk first and then `dotnet new --install` sourcing from disk.

Should this work? or is this a gap in compatibility between `dotnet net --install` and Azure DevOps?

**Comment by vlada-shubina** [comment]
@danijam what versions are you at? can you dump `dotnet --info` output please?

**Comment by vlada-shubina** [comment]
Thanks @danijam 

Could you please try to run verbose output for this command by setting `DOTNET_CLI_CONTEXT_VERBOSE` env variable to `true` before running it? 

It should give more information on this error.

Thank you

**Comment by danijam** [comment]
Thanks @vlada-shubina
So running:
```
$env:DOTNET_CLI_CONTEXT_VERBOSE = 'True'
dotnet new --install <redacted> --nuget-source "https://pkgs.dev.azure.com/<redacted>/<redacted>/_packaging/<redacted>/nuget/v3/index.json"
```

Output:
```
Telemetry is: Enabled
[2021-12-03 12:55:18.795] [Debug] [Microsoft.TemplateEngine.Cli.CliTemplateEngineHost] => [Execute]: Execute started
The following template packages will be installed:
   <redacted>

[2021-12-03 12:55:18.821] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: <redacted> is not a local NuGet package.
[2021-12-03 12:55:18.836] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: <redacted> is identified as the downloadable NuGet package.
[2021-12-03 12:55:18.841] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: <redacted> is not a local NuGet package.
[2021-12-03 12:55:18.841] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: <redacted> is identified as the downloadable NuGet package.
[2021-12-03 12:55:18.865] [Debug] [NuGetLogger] => [Execute]: Searching for <redacted> in https://pkgs.dev.azure.com/<redacted>/<redacted>/_packaging/<redacted>/nuget/v3/index.json.
[2021-12-03 12:55:18.994] [Debug] [NuGetLogger] => [Execute]: Searching for <redacted> in https://api.nuget.org/v3/index.json.
[2021-12-03 12:55:19.020] [Debug] [NuGetLogger] => [Execute]:   GET https://api.nuget.org/v3/registration5-gz-semver2/<redacted>/index.json
[2021-12-03 12:55:19.023] [Debug] [NuGetLogger] => [Execute]: Searching for <redacted> in C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\.
[2021-12-03 12:55:19.029] [Debug] [NuGetLogger] => [Execute]: <redacted> is not found in NuGet feed C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\.
Error: Failed to read package information from NuGet source https://pkgs.dev.azure.com/<redacted>/<redacted>/_packaging/<redacted>/nuget/v3/index.json.
[2021-12-03 12:55:19.488] [Debug] [NuGetLogger] => [Execute]: Details: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://pkgs.dev.azure.com/<redacted>/<redacted>/_packaging/<redacted>/nuget/v3/index.json.
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetApiPackageManager.GetPackageMetadataAsync(PackageSource source, String packageIdentifier, Boolean includePrerelease, CancellationToken cancellationToken).
[2021-12-03 12:55:19.503] [Debug] [NuGetLogger] => [Execute]:   NotFound https://api.nuget.org/v3/registration5-gz-semver2/<redacted>/index.json 482ms
[2021-12-03 12:55:19.507] [Debug] [NuGetLogger] => [Execute]: <redacted> is not found in NuGet feed https://api.nuget.org/v3/index.json.
Warning: <redacted>y is not found in NuGet feeds https://pkgs.dev.azure.com/<redacted>/<redacted>/_packaging/<redacted>/nuget/v3/index.json, https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\.
<redacted> could not be installed, the package does not exist.
[2021-12-03 12:55:19.546] [Debug] [Microsoft.TemplateEngine.Cli.CliTemplateEngineHost] => [Execute]: Execute finished, took 753 ms
```

So looks I'm not getting authorised.

**Comment by vlada-shubina** [comment]
@danijam do you have [credential provider](https://github.com/microsoft/artifacts-credprovider) installed?

it looks like the same issue as here: https://github.com/dotnet/templating/issues/2212#issuecomment-845159319
https://github.com/dotnet/templating/issues/1747#issuecomment-618519996

**Comment by danijam** [comment]
Update. Turns out my `dotnet restore` is not working either. Unauthorised. Only seems to work when done from Visual Studio. Looks like I needed to install the Microsoft Artifacts Credential Provider: https://github.com/Microsoft/artifacts-credprovider

Added the release `netcore` directory to my `$env:UserProfile\.nuget\plugins` and was able to successfully auth using `dotnet new` with the azure devops artifact feed source. It does need the --interactive options as it starts a AAD device login flow.

Oddly it needed me todo it twice... Output: 
```
The following template packages will be installed:
   <redacted>

[NuGet Manager]     [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/<redacted>/<redacted>/_packaging/<redacted>/nuget/v3/index.json
[NuGet Manager]     [CredentialProvider]ATTENTION: User interaction required.

    **********************************************************************

    To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <redacted>to authenticate.

    **********************************************************************

[NuGet Manager] [Info]     [CredentialProvider]VstsCredentialProvider - Acquired bearer token using 'ADAL Device Code'
[NuGet Manager] [Info]     [CredentialProvider]VstsCredentialProvider - Attempting to exchange the bearer token for an Azure DevOps session token.
[NuGet Manager]     [CredentialProvider]DeviceFlow: https://pkgs.dev.azure.com/<redacted>/<redacted>/_packaging/<redacted>/nuget/v3/index.json
[NuGet Manager]     [CredentialProvider]ATTENTION: User interaction required.

    **********************************************************************

    To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <redacted> to authenticate.

    **********************************************************************

[NuGet Manager] [Info]     [CredentialProvider]VstsCredentialProvider - Acquired bearer token using 'ADAL Device Code'
[NuGet Manager] [Info]     [CredentialProvider]VstsCredentialProvider - Attempting to exchange the bearer token for an Azure DevOps session token.
Success: <redacted> installed the following templates:
Template Name                          Short Name           Language  Tags
-------------------------------------  -------------------  --------  ---------------------------------
<redacted>  <redacted>  [C#]      <redacted>
```

**Comment by danijam** [comment]
@vlada-shubina Yes that looks like the root cause. See my previous message. Do you know more broadly speaking if there are plans to make this authentication experience more seemless, or where that particular concern sits? Purely coming at this from a user experience perspective I've got to make sure I write instructions that cover off installation of the credential provider and putting up with the hoops necessary to follow the device code flow for AAD which isn't very "nice"

Thanks for the help.

**Comment by vlada-shubina** [comment]
@danijam I've created https://github.com/NuGet/Home/issues/11435 for considerations on how to improve this experience.
As this is not actionable for `dotnet new`, I'm closing this issue, please follow up and feel free to give a feedback in the other one if needed.
