### ISSUE TITLE
dotnet new -i always returning failed to download error 

### ISSUE THREAD

**Issue by mika76** [dotnet/templating#4176]
> dotnet 6 - macos big sur 11.6 - zsh

If I type in 
`dotnet new -i TryPhotino.VSCode.Project.Templates` (or any other template)

I get
```
Warning: Failed to download TryPhotino.VSCode.Project.Templates::2.0.1 from NuGet feed https://api.nuget.org/v3/index.json.
TryPhotino.VSCode.Project.Templates could not be installed, download failed.
```

but I can access https://api.nuget.org/v3/index.json in my browser with no problems, and if I try to use the dotnet cli to install a package into a console app, like...

`dotnet add package Photino.NET --version 2.1.10`

I get
```
  Determining projects to restore...
  Writing /var/folders/d8/rfmf5v3j70s4jxtpw70c59k40000gn/T/tmpFC9sOg.tmp
info : Adding PackageReference for package 'Photino.NET' into project '/Users/mm/Documents/test/test.csproj'.
info : Restoring packages for /Users/mm/Documents/test/test.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/photino.net/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/photino.net/index.json 355ms
info :   GET https://api.nuget.org/v3-flatcontainer/photino.net/2.1.10/photino.net.2.1.10.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/photino.net/2.1.10/photino.net.2.1.10.nupkg 493ms
info :   GET https://api.nuget.org/v3-flatcontainer/photino.native/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/photino.native/index.json 473ms
info :   GET https://api.nuget.org/v3-flatcontainer/photino.native/2.1.3/photino.native.2.1.3.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/photino.native/2.1.3/photino.native.2.1.3.nupkg 513ms
info : Installed Photino.Native 2.1.3 from https://api.nuget.org/v3/index.json with content hash wsf5oNrpmPFki6Lh5ql9+g9rUPlvn5BZLZkPND7Eeq9zgPyXIPWv05cyQUV4foI29One5s73RlakDmOEDwHtSQ==.
info : Installed Photino.NET 2.1.10 from https://api.nuget.org/v3/index.json with content hash Ov34z+9jlSncLs8EEA4S0pv0qcTtEhuUR5pF0qORDoRtD8RSLSw2WAeWQzJUh0dRVHtgZY8f2uCvfm27TiElEQ==.
info : Package 'Photino.NET' is compatible with all the specified frameworks in project '/Users/mm/Documents/test/test.csproj'.
info : PackageReference for package 'Photino.NET' version '2.1.10' added to file '/Users/mm/Documents/test/test.csproj'.
info : Committing restore...
info : Writing assets file to disk. Path: /Users/mm/Documents/test/obj/project.assets.json
log  : Restored /Users/mm/Documents/test/test.csproj (in 2.27 sec).
```

All seems to work fine... 

So I'm confused :smile:

**Comment by vlada-shubina** [comment]
@mika76 

Could you please try to run verbose output for install command by setting DOTNET_CLI_CONTEXT_VERBOSE env variable to true before running it?
It should give more information on this error.

Thank you

**Comment by mika76** [comment]
```
➜  ~ dotnet new -i TryPhotino.VSCode.Project.Templates
Telemetry is: Enabled
[2021-12-08 12:18:14.758] [Debug] [Microsoft.TemplateEngine.Cli.CliTemplateEngineHost] => [Execute]: Execute started
The following template packages will be installed:
   TryPhotino.VSCode.Project.Templates

[2021-12-08 12:18:14.792] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: TryPhotino.VSCode.Project.Templates is not a local NuGet package.
[2021-12-08 12:18:14.803] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: TryPhotino.VSCode.Project.Templates is identified as the downloadable NuGet package.
[2021-12-08 12:18:14.806] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: TryPhotino.VSCode.Project.Templates is not a local NuGet package.
[2021-12-08 12:18:14.806] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: TryPhotino.VSCode.Project.Templates is identified as the downloadable NuGet package.
[2021-12-08 12:18:14.822] [Debug] [NuGetLogger] => [Execute]: Searching for TryPhotino.VSCode.Project.Templates in https://api.nuget.org/v3/index.json.
[2021-12-08 12:18:15.127] [Debug] [NuGetLogger] => [Execute]:   GET https://api.nuget.org/v3/registration5-gz-semver2/tryphotino.vscode.project.templates/index.json
[2021-12-08 12:18:15.597] [Debug] [NuGetLogger] => [Execute]:   OK https://api.nuget.org/v3/registration5-gz-semver2/tryphotino.vscode.project.templates/index.json 470ms
[2021-12-08 12:18:15.668] [Debug] [NuGetLogger] => [Execute]: Found 5 versions for TryPhotino.VSCode.Project.Templates in NuGet feed https://api.nuget.org/v3/index.json.
Warning: Failed to download TryPhotino.VSCode.Project.Templates::2.0.1 from NuGet feed https://api.nuget.org/v3/index.json.
[2021-12-08 12:18:15.828] [Debug] [NuGetLogger] => [Execute]: Details: System.UnauthorizedAccessException: Access to the path '/Users/mika/.templateengine/packages/TryPhotino.VSCode.Project.Templates.2.0.1.nupkg' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Create(String path)
   at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetApiPackageManager.DownloadPackageAsync(String downloadPath, String identifier, String version, IEnumerable`1 additionalSources, CancellationToken cancellationToken).
TryPhotino.VSCode.Project.Templates could not be installed, download failed.
[2021-12-08 12:18:15.837] [Debug] [Microsoft.TemplateEngine.Cli.CliTemplateEngineHost] => [Execute]: Execute finished, took 1081 ms
```

Interesting, so it's a permission problem on my .templateengine directory. How would this happen? I don't think I've done anything weird when installing .net or any templates before...

**Comment by vlada-shubina** [comment]
@mika76 

`dotnet new` is using `/Users/<user>/.templateengine/` folder to store the settings for at least couple of releases, so definitely no change here with .NET 6.

could you please check the permissions on `.templateengine` and `packages` folder,  whether `dotnet new` was able to write anything to `/Users/mika/.templateengine/` folder (it should also write settings files there) and if it is possible to write anything at all to this folder/subfolders (create new file or copy file)? Also I noticed that during restore other folder was used (`/Users/mm/Documents/`).

It looks like an issue with permissions on that folder (or `packages` subfolder), but if it's the case, likely any other command for dotnet new will fail too, because it won't be able to save the cache.

**Comment by mika76** [comment]
Ok cool, I noticed my .templateengine/packages directory had different permissions set than the other ones, so I changed it to be the same and it works fine now. Weird, but at least it works now.

Thanks for your help...
