### ISSUE TITLE
Exception when defining post-actions argument properties as string instead of array

### ISSUE THREAD

**Issue by Tasteful** [dotnet/templating#4179]
Regarding to 
- https://github.com/dotnet/templating/wiki/Post-Action-Registry#add-a-reference-to-a-project-file the `targetFiles` should be able to be a `string` or `array`
- https://github.com/dotnet/templating/wiki/Post-Action-Registry#add-projects-to-a-solution-file the `projectFiles` should be able to be a `string` or `array`

In both if this places if we passing in a `string` instead of the `array` we are getting the following exception and without build a debug version of the dotnet-new3 tool it was impossible to find out why it not was working.
```
Post action failed.
Details: Newtonsoft.Json.JsonReaderException: Input string '.' is not a valid number. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json)
   at Microsoft.TemplateEngine.Cli.PostActionProcessors.AddProjectsToSolutionPostAction.Process(IEngineEnvironmentSettings environment, IPostAction action, ICreationEffects creationEffects, ICreationResult templateCreationResult, String outputBasePath) in D:\GitHub\templating\src\Microsoft.TemplateEngine.Cli\PostActionProcessors\AddProjectsToSolutionPostAction.cs:line 38
   at Microsoft.TemplateEngine.Cli.PostActionDispatcher.ProcessAction(ICreationEffects creationEffects, ICreationResult creationResult, String outputBaseDirectory, IPostAction action, IPostActionProcessor actionProcessor) in D:\GitHub\templating\src\Microsoft.TemplateEngine.Cli\PostActionDispatcher.cs:line 230
```

The issue is in the following lines where an parsing of the value; if entered as a string, is failing due to malformed json. To be able to parse this as a string, the content need to be quoted `"MyString"` but as now they are unquoted `MyString`.
https://github.com/dotnet/templating/blob/b01f72accf138c77b9a577d683062cd69b745322/src/Microsoft.TemplateEngine.Cli/PostActionProcessors/AddReferencePostActionProcessor.cs#L30
https://github.com/dotnet/templating/blob/b01f72accf138c77b9a577d683062cd69b745322/src/Microsoft.TemplateEngine.Cli/PostActionProcessors/AddProjectsToSolutionPostAction.cs#L38

**Comment by vlada-shubina** [comment]
That's a weird behavior of Newtonsoft.JSON, found couple issues with that, https://github.com/JamesNK/Newtonsoft.Json/issues/248.

This doesn't work
```C#
            string json =
@"
{
  'args': {
    'targetFilesStr': 'target',
    'targetFilesArr': ['t1', 't2']
  }
}";

            JToken jsonP = JToken.Parse(json);
            foreach (var prop in jsonP.PropertiesOf("args"))
            {
                JToken.Parse(prop.Value.ToString());
            }
```

This works
```C#
            string json =
@"
{
  'args': {
    'targetFilesStr': 'target',
    'targetFilesArr': ['t1', 't2']
  }
}";

In any case, needs fix.

            JToken jsonP = JToken.Parse(json);
            foreach (var prop in jsonP.PropertiesOf("args"))
            {
                JToken.Parse(prop.Value.ToString(Formatting.None));
            }


```
