### ISSUE TITLE
dotnet new 401 unauthorized errors

### ISSUE THREAD

**Issue by levimatheri** [dotnet/templating#4278]
After running with `--interactive` from a private NuGet feed, the template is installed. I would expect the token to be cached so I don't have to use `--interactive` every time. However, reinstalling the same template results in the error below (with telemetry enabled):

```
Telemetry is: Enabled
[2022-01-20 18:22:16.205] [Debug] [Microsoft.TemplateEngine.Cli.CliTemplateEngineHost] => [Execute]: Execute started
The following template packages will be installed:
   <package>

[2022-01-20 18:22:16.273] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: <package> is not a local NuGet package.
[2022-01-20 18:22:16.299] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: <package> is identified as the downloadable NuGet package.
[2022-01-20 18:22:16.307] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: <package> is not a local NuGet package.
[2022-01-20 18:22:16.307] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: <package> is identified as the downloadable NuGet package.
[2022-01-20 18:22:16.348] [Debug] [NuGetLogger] => [Execute]: Searching for <package> in https://api.nuget.org/v3/index.json.
[2022-01-20 18:22:16.441] [Debug] [NuGetLogger] => [Execute]:   GET https://api.nuget.org/v3/registration5-gz-semver2/<package>/index.json
[2022-01-20 18:22:16.542] [Debug] [NuGetLogger] => [Execute]: Searching for <package> in C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\.
[2022-01-20 18:22:16.552] [Debug] [NuGetLogger] => [Execute]: Searching for <package> in https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json.
[2022-01-20 18:22:16.554] [Debug] [NuGetLogger] => [Execute]: <package> is not found in NuGet feed C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\.
[2022-01-20 18:22:16.558] [Debug] [NuGetLogger] => [Execute]:   GET https://pkgs.dev.azure.com/<organization>/_packaging/59388b54-2798-4d11-b0d7-a731a1308e1e/nuget/v3/registrations2-semver2/<package>/index.json
[2022-01-20 18:22:17.127] [Debug] [NuGetLogger] => [Execute]:   NotFound https://api.nuget.org/v3/registration5-gz-semver2/<package>/index.json 683ms
[2022-01-20 18:22:17.146] [Debug] [NuGetLogger] => [Execute]: <package> is not found in NuGet feed https://api.nuget.org/v3/index.json.
[NuGet Manager] [DEBUG] Using C:\Users\levim\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll as a credential provider plugin.
[NuGet Manager] [Verbose]     [CredentialProvider.182218]Running in plug-in mode
[NuGet Manager] [Verbose]     [CredentialProvider.182218]Command-line v0.1.28+103227dd070f2b048ce0ae9bc259f12d509d85e2: C:\Users\levim\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll -Plugin
[NuGet Manager] [Verbose]     [CredentialProvider.182218]Handling 'Request' 'Initialize'. Time elapsed in ms: 5 - Payload: {"ClientVersion":"6.0.0","Culture":"en-US","RequestTimeout":"00:00:05"}
[NuGet Manager] [Verbose]     [CredentialProvider.182218]Sending response: 'Request' 'Initialize'. Time elapsed in ms: 7
[NuGet Manager] [Verbose]     [CredentialProvider.182218]Time elapsed in milliseconds after sending response 'Request' 'Initialize': 10
[NuGet Manager] [Verbose]     [CredentialProvider.182218]Handling 'Request' 'GetOperationClaims'. Time elapsed in ms: 1 - Payload: {}
[NuGet Manager] [Verbose]     [CredentialProvider.182218]Sending response: 'Request' 'GetOperationClaims'. Time elapsed in ms: 12
[NuGet Manager] [Verbose]     [CredentialProvider.182218]Time elapsed in milliseconds after sending response 'Request' 'GetOperationClaims': 28
[NuGet Manager] [Verbose]     [CredentialProvider.182218]Handling 'Request' 'SetLogLevel'. Time elapsed in ms: 6 - Payload: {"LogLevel":"Debug"}
[NuGet Manager] [Verbose]     [CredentialProvider]Sending response: 'Request' 'SetLogLevel'. Time elapsed in ms: 7
[NuGet Manager] [Verbose]     [CredentialProvider]Time elapsed in milliseconds after sending response 'Request' 'SetLogLevel': 23
[NuGet Manager] [Verbose]     [CredentialProvider]Handling 'Request' 'GetAuthenticationCredentials'. Time elapsed in ms: 10 - Payload: {"Uri":"https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json","IsRetry":false,"IsNonInteractive":true,"CanShowDialog":false}
[NuGet Manager] [Verbose]     [CredentialProvider]Creating a progress reporter with interval: 00:00:02
[NuGet Manager] [Verbose]     [CredentialProvider]Handling auth request, Uri: https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json, IsRetry: False, IsNonInteractive: True, CanShowDialog: False
[NuGet Manager] [Verbose]     [CredentialProvider]URI: https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json
[NuGet Manager] [Verbose]     [CredentialProvider]VstsBuildTaskServiceEndpointCredentialProvider - This credential provider must be run under the Team Build tasks for NuGet with external endpoint credentials. Appropriate environment variable needs to be set.
[NuGet Manager] [Verbose]     [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.VstsBuildTaskServiceEndpoint.VstsBuildTaskServiceEndpointCredentialProvider, cannot provide credentials for https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json
[NuGet Manager] [Verbose]     [CredentialProvider]VstsBuildTaskCredentialProvider - This credential provider must be run under the Team Build tasks for NuGet. Appropriate environment variables must be set.
[NuGet Manager] [Verbose]     [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.VstsBuildTask.VstsBuildTaskCredentialProvider, cannot provide credentials for https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json
[NuGet Manager] [Verbose]     [CredentialProvider]GET https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json
[NuGet Manager] [Verbose]     [CredentialProvider]VstsCredentialProvider - Detected a hosted Azure DevOps Service.
[NuGet Manager] [Verbose]     [CredentialProvider]Using NuGetCredentialProvider.CredentialProviders.Vsts.VstsCredentialProvider to try to get credentials for https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json.
[NuGet Manager] [Verbose]     [CredentialProvider]IsRetry: False
[NuGet Manager] [Verbose]     [CredentialProvider]Could not find cached SessionToken for https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json
[NuGet Manager] [Verbose]     [CredentialProvider]GET https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json
[NuGet Manager] [Verbose]     [CredentialProvider]Found AAD Authority from 401 headers: https://login.windows.net/8b3dd73e-4e72-4679-b191-56da1588712b
[NuGet Manager] [Verbose]     [CredentialProvider]VstsCredentialProvider - Using AAD authority: https://login.windows.net/8b3dd73e-4e72-4679-b191-56da1588712b
[NuGet Manager] [Verbose]     [CredentialProvider]VstsCredentialProvider - Attempting to acquire bearer token using provider 'ADAL Cache'
[NuGet Manager] [Verbose]     [CredentialProvider]VstsCredentialProvider - Bearer token provider 'ADAL Cache' didn't acquire a token
[NuGet Manager] [Verbose]     [CredentialProvider]VstsCredentialProvider - Attempting to acquire bearer token using provider 'ADAL Windows Integrated Authentication'
[NuGet Manager] [Warning] The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
[2022-01-20 18:22:19.853] [Debug] [NuGetLogger] => [Execute]:   Unauthorized https://pkgs.dev.azure.com/<organization>/_packaging/59388b54-2798-4d11-b0d7-a731a1308e1e/nuget/v3/registrations2-semver2/<package>/index.json 680ms
Error: Failed to read package information from NuGet source https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json.
[2022-01-20 18:22:19.884] [Debug] [NuGetLogger] => [Execute]: Details: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.LoadRegistrationIndexAsync(HttpSource httpSource, Uri registrationUri, String packageId, SourceCacheContext cacheContext, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.GetMetadataAsync(String packageId, Boolean includePrerelease, Boolean includeUnlisted, VersionRange range, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.GetMetadataAsync(String packageId, Boolean includePrerelease, Boolean includeUnlisted, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)
   at Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetApiPackageManager.GetPackageMetadataAsync(PackageSource source, String packageIdentifier, Boolean includePrerelease, CancellationToken cancellationToken).
[NuGet Manager] [Verbose]     [CredentialProvider]VstsCredentialProvider - Bearer token provider 'ADAL Windows Integrated Authentication' didn't acquire a token
[NuGet Manager] [Verbose]     [CredentialProvider]VstsCredentialProvider - Not running bearer token provider 'ADAL UI'
[NuGet Manager] [Verbose]     [CredentialProvider]VstsCredentialProvider - Not running bearer token provider 'ADAL Device Code'
Warning: <package> is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\, https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json.
[NuGet Manager] [Verbose]     [CredentialProvider]VstsCredentialProvider - Could not obtain credentials for https://pkgs.dev.azure.com/<organization>/_packaging/<feed>/nuget/v3/index.json
[NuGet Manager] [Verbose]     [CredentialProvider]Unable to acquire credentials.
[NuGet Manager] [Verbose]     [CredentialProvider]Sending response: 'Request' 'GetAuthenticationCredentials'. Time elapsed in ms: 1553
[NuGet Manager] [Verbose]     [CredentialProvider]Time elapsed in milliseconds after sending response 'Request' 'GetAuthenticationCredentials': 1559
<package> could not be installed, the package does not exist.
[2022-01-20 18:22:19.924] [Debug] [Microsoft.TemplateEngine.Cli.CliTemplateEngineHost] => [Execute]: Execute finished, took 3724 ms
```

dotnet info:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by DavidKarlas** [comment]
Hi,

this is what I tried:
```
PS C:\Users\davkar\tmp\test> dotnet new -i bla --interactive --nuget-source https://devdiv.pkgs.visualstudio.com/_packaging/vssdk/nuget/v3/index.json
Telemetry is: Enabled
[2022-01-24 14:01:21.894] [Debug] [Microsoft.TemplateEngine.Cli.CliTemplateEngineHost] => [Execute]: Execute started
The following template packages will be installed:
   bla

[2022-01-24 14:01:21.913] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: bla is not a local NuGet package.
[2022-01-24 14:01:21.926] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: bla is identified as the downloadable NuGet package.
[2022-01-24 14:01:21.929] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: bla is not a local NuGet package.
[2022-01-24 14:01:21.929] [Debug] [Microsoft.TemplateEngine.Edge.Installers.NuGet.NuGetInstaller] => [Execute]: bla is identified as the downloadable NuGet package.
[2022-01-24 14:01:21.943] [Debug] [NuGetLogger] => [Execute]: Searching for bla in https://devdiv.pkgs.visualstudio.com/_packaging/vssdk/nuget/v3/index.json.
[2022-01-24 14:01:21.974] [Debug] [NuGetLogger] => [Execute]:   GET https://devdiv.pkgs.visualstudio.com/_packaging/d14bf48a-f184-456a-b267-b5d008678963/nuget/v3/registrations2-semver2/bla/index.json
[2022-01-24 14:01:22.022] [Debug] [NuGetLogger] => [Execute]: Searching for bla in https://api.nuget.org/v3/index.json.
[2022-01-24 14:01:22.024] [Debug] [NuGetLogger] => [Execute]:   GET https://api.nuget.org/v3/registration5-gz-semver2/bla/index.json
[2022-01-24 14:01:22.025] [Debug] [NuGetLogger] => [Execute]: Searching for bla in https://www.myget.org/F/nettopologysuite/api/v3/index.json.
[2022-01-24 14:01:22.027] [Debug] [NuGetLogger] => [Execute]:   GET https://www.myget.org/F/nettopologysuite/api/v3/registration1/bla/index.json
[2022-01-24 14:01:22.027] [Debug] [NuGetLogger] => [Execute]: Searching for bla in C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\.
[2022-01-24 14:01:22.031] [Debug] [NuGetLogger] => [Execute]: bla is not found in NuGet feed C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\.
[2022-01-24 14:01:22.243] [Debug] [NuGetLogger] => [Execute]:   NotFound https://www.myget.org/F/nettopologysuite/api/v3/registration1/bla/index.json 215ms
[2022-01-24 14:01:22.250] [Debug] [NuGetLogger] => [Execute]: bla is not found in NuGet feed https://www.myget.org/F/nettopologysuite/api/v3/index.json.
[2022-01-24 14:01:22.566] [Debug] [NuGetLogger] => [Execute]:   NotFound https://api.nuget.org/v3/registration5-gz-semver2/bla/index.json 541ms
[2022-01-24 14:01:22.567] [Debug] [NuGetLogger] => [Execute]: bla is not found in NuGet feed https://api.nuget.org/v3/index.json.
[NuGet Manager] [DEBUG] Using C:\Users\davkar\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll as a credential provider plugin.
[NuGet Manager] [Verbose]     [CredentialProvider.140123]Running in plug-in mode
[NuGet Manager] [Verbose]     [CredentialProvider.140123]Command-line v0.1.28+103227dd070f2b048ce0ae9bc259f12d509d85e2: C:\Users\davkar\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll -Plugin
[NuGet Manager] [Verbose]     [CredentialProvider.140123]Handling 'Request' 'Initialize'. Time elapsed in ms: 2 - Payload: {"ClientVersion":"6.1.0","Culture":"en-SI","RequestTimeout":"00:00:05"}
[NuGet Manager] [Verbose]     [CredentialProvider.140123]Sending response: 'Request' 'Initialize'. Time elapsed in ms: 2
[NuGet Manager] [Verbose]     [CredentialProvider.140123]Time elapsed in milliseconds after sending response 'Request' 'Initialize': 3
[NuGet Manager] [Verbose]     [CredentialProvider.140123]Handling 'Request' 'GetOperationClaims'. Time elapsed in ms: 0 - Payload: {}
[NuGet Manager] [Verbose]     [CredentialProvider.140123]Sending response: 'Request' 'GetOperationClaims'. Time elapsed in ms: 3
[NuGet Manager] [Verbose]     [CredentialProvider.140123]Time elapsed in milliseconds after sending response 'Request' 'GetOperationClaims': 8
[NuGet Manager] [Verbose]     [CredentialProvider.140123]Handling 'Request' 'SetLogLevel'. Time elapsed in ms: 0 - Payload: {"LogLevel":"Debug"}
[NuGet Manager] [Verbose]     [CredentialProvider]Sending response: 'Request' 'SetLogLevel'. Time elapsed in ms: 1
[NuGet Manager] [Verbose]     [CredentialProvider]Time elapsed in milliseconds after sending response 'Request' 'SetLogLevel': 4
[NuGet Manager] [Verbose]     [CredentialProvider]Handling 'Request' 'GetAuthenticationCredentials'. Time elapsed in ms: 2 - Payload: {"Uri":"https://devdiv.pkgs.visualstudio.com/_packaging/vssdk/nuget/v3/index.json","IsRetry":false,"IsNonInteractive":false,"CanShowDialog":false}
[NuGet Manager] [Verbose]     [CredentialProvider]Creating a progress reporter with interval: 00:00:02
[NuGet Manager] [Verbose]     [CredentialProvider]Handling auth request, Uri: https://devdiv.pkgs.visualstudio.com/_packaging/vssdk/nuget/v3/index.json, IsRetry: False, IsNonInteractive: False, CanShowDialog: False
[NuGet Manager] [Verbose]     [CredentialProvider]URI: https://devdiv.pkgs.visualstudio.com/_packaging/vssdk/nuget/v3/index.json
[NuGet Manager] [Verbose]     [CredentialProvider]VstsBuildTaskServiceEndpointCredentialProvider - This credential provider must be run under the Team Build tasks for NuGet with external endpoint credentials. Appropriate environment variable needs to be set.
[NuGet Manager] [Verbose]     [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.VstsBuildTaskServiceEndpoint.VstsBuildTaskServiceEndpointCredentialProvider, cannot provide credentials for https://devdiv.pkgs.visualstudio.com/_packaging/vssdk/nuget/v3/index.json
[NuGet Manager] [Verbose]     [CredentialProvider]VstsBuildTaskCredentialProvider - This credential provider must be run under the Team Build tasks for NuGet. Appropriate environment variables must be set.
[NuGet Manager] [Verbose]     [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.VstsBuildTask.VstsBuildTaskCredentialProvider, cannot provide credentials for https://devdiv.pkgs.visualstudio.com/_packaging/vssdk/nuget/v3/index.json
[NuGet Manager] [Verbose]     [CredentialProvider]VstsCredentialProvider - Matched well-known Azure DevOps Service hostname: devdiv.pkgs.visualstudio.com
[NuGet Manager] [Verbose]     [CredentialProvider]Using NuGetCredentialProvider.CredentialProviders.Vsts.VstsCredentialProvider to try to get credentials for https://devdiv.pkgs.visualstudio.com/_packaging/vssdk/nuget/v3/index.json.
[NuGet Manager] [Verbose]     [CredentialProvider]IsRetry: False
[NuGet Manager] [Verbose]     [CredentialProvider]Found cached SessionToken for https://devdiv.pkgs.visualstudio.com/_packaging/vssdk/nuget/v3/index.json
[NuGet Manager] [Verbose]     [CredentialProvider]Sending response: 'Request' 'GetAuthenticationCredentials'. Time elapsed in ms: 18
[NuGet Manager] [Verbose]     [CredentialProvider]Time elapsed in milliseconds after sending response 'Request' 'GetAuthenticationCredentials': 20
[2022-01-24 14:01:24.024] [Debug] [NuGetLogger] => [Execute]:   NotFound https://devdiv.pkgs.visualstudio.com/_packaging/d14bf48a-f184-456a-b267-b5d008678963/nuget/v3/registrations2-semver2/bla/index.json 1664ms
[2022-01-24 14:01:24.024] [Debug] [NuGetLogger] => [Execute]: bla is not found in NuGet feed https://devdiv.pkgs.visualstudio.com/_packaging/vssdk/nuget/v3/index.json.
Warning: bla is not found in NuGet feeds https://devdiv.pkgs.visualstudio.com/_packaging/vssdk/nuget/v3/index.json, https://api.nuget.org/v3/index.json, https://www.myget.org/F/nettopologysuite/api/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\.
bla could not be installed, the package does not exist.
[2022-01-24 14:01:24.037] [Debug] [Microsoft.TemplateEngine.Cli.CliTemplateEngineHost] => [Execute]: Execute finished, took 2144 ms
```

Can you try deleting content of `C:\Users\davkar\AppData\Local\MicrosoftCredentialProvider` folder and see if that fixes it?

**Comment by levimatheri** [comment]
@DavidKarlas I tried deleting the folder contents with no success. It seems something is setting `IsRetry` to true and invalidating the cache 
![image](https://user-images.githubusercontent.com/16405269/150810408-0e3e1f50-2240-4a7c-b605-114d642d13ad.png)

**Comment by levimatheri** [comment]
@DavidKarlas I even tried in a new provisioned VM in Azure with latest .NET 6 SDK, and got same errors.

**Comment by DavidKarlas** [comment]
OK, let me try tomorrow morning on fresh VM to see if I can repro

**Comment by DavidKarlas** [comment]
Also, you are using "https://microsoft.com/devicelogin" to do login or some other method?
Is cache working if you are doing `dotnet restore` on some project from that feed?

**Comment by levimatheri** [comment]
> Also, you are using "https://microsoft.com/devicelogin" to do login or some other method? Is cache working if you are doing `dotnet restore` on some project from that feed?

Yes, I'm using "https://microsoft.com/devicelogin" to do login.
Cache _is_ working if I do `dotnet restore`, yes

**Comment by DavidKarlas** [comment]
What command are you using? Do you specify `--interactive`? If you specify it does it use cache? Also are you using `https://OrganistationName.pkgs.visualstudio.com/_packaging/FeedName/nuget/v3/index.json` or `https://pkgs.visualstudio.com/OrganistationName/_packaging/FeedName/nuget/v3/index.json` style of URL?

**Comment by levimatheri** [comment]
@DavidKarlas If I specify `--interactive` a second time it still prompts me for credentials. I've tried using both styles for the feed URL, but getting same result.

**Comment by levimatheri** [comment]
@DavidKarlas I tried with `https://OrganistationName.pkgs.visualstudio.com/_packaging/FeedName/nuget/v3/index.json` style for the package feed, and got the same error.

**Comment by vlada-shubina** [comment]
It looks that the issue is in inconsistency between provider and NuGet.Client `isRetry` implementation. 
Client sends the auth request with `isRetry = true` on any consequent request after first successful request(https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Core/NuGet.Credentials/CredentialService.cs#L93), whereas providers treats `isRetry = true` as signal invalidate the cache and re-login(https://github.com/microsoft/artifacts-credprovider/blob/6effb16ce7aed80f8d3e3092e79c9cd3044f3f66/CredentialProvider.Microsoft/RequestHandlers/GetAuthenticationCredentialsRequestHandler.cs#L139-L159)

There is barely nothing we can do on `dotnet new` side to change this behavior, the fix should be likely on credential provider side.

**Comment by levimatheri** [comment]
Thanks @vlada-shubina

**Comment by OskarKlintrot** [comment]
Is this tracked somewhere? [NuGet.Client](https://github.com/NuGet/NuGet.Client) doesn't have any issues and [artifacts-credprovider](https://github.com/microsoft/artifacts-credprovider) just closes everything and refers to the Developer Community instead.

**Comment by vlada-shubina** [comment]
I'll reopen this issue to track it for now.

**Comment by levimatheri** [comment]
Oddly enough, installing .NET 5 runtime fixed it for me LOL @OskarKlintrot

**Comment by OskarKlintrot** [comment]
That's really odd @levimatheri! Unfortunately I already have dotnet 5 installed so I guess it won't help me.

**Comment by DavidKarlas** [comment]
Sorry this slipped my mind, I will try to open PR against Provider this week...

**Comment by DavidKarlas** [comment]
Just quick update, didn't slip my mind this time... :)
Here is the problem: https://github.com/NuGet/Home/issues/11698

**Comment by DavidKarlas** [comment]
Opened bug at https://github.com/NuGet/Home/issues/11801
