### ISSUE TITLE
Investigate search cache pipeline issues

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#5344]
[Search cache pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=1025&_a=summary) still fails quite often due to
- random test failures - hopefully https://github.com/dotnet/templating/pull/5338 fixes it
- install of Azure CLI failures

Suggesting to implement retries for installing failures, or any other suggestions are welcome.

**Comment by GangWang01** [comment]
From the log of CI runs and test log, the random test failure is Microsoft.TemplateEngine.Edge.UnitTests.TestFileWatcher.  Please see the log below. 
```
Unhandled exception. [2022-10-18 13:07:35.656] dbug: NuGetLogger[0] Searching for Microsoft.DotNet.Common.ProjectTemplates.5.0 in https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json.
System.IO.IOException: The process cannot access the file '/tmp/TemplateEngine.Tests/fe691cb1-7d8f-47ec-b8f8-4bab5c1bd93f/settings.json' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.OpenRead(String path) in /mnt/vss/_work/1/s/src/Microsoft.TemplateEngine.Utils/PhysicalFileSystem.cs:line 84
   at Microsoft.TemplateEngine.TestHelper.MonitoredFileSystem.OpenRead(String path) in /mnt/vss/_work/1/s/test/Microsoft.TemplateEngine.TestHelper/MonitoredFileSystem.cs:line 67
   at Microsoft.TemplateEngine.JExtensions.ReadObject(IPhysicalFileSystem fileSystem, String path) in /mnt/vss/_work/1/s/src/Shared/JExtensions.cs:line 347
   at Microsoft.TemplateEngine.Edge.BuiltInManagedProvider.GlobalSettings.GetInstalledTemplatePackagesAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/src/Microsoft.TemplateEngine.Edge/BuiltInManagedProvider/GlobalSettings.cs:line 87
   at Microsoft.TemplateEngine.Edge.UnitTests.GlobalSettingsTests.<>c__DisplayClass3_0.<<TestFileWatcher>b__0>d.MoveNext() in /mnt/vss/_work/1/s/test/Microsoft.TemplateEngine.Edge.UnitTests/GlobalSettingsTests.cs:line 54
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Aborted (core dumped)
```
It seems the following case happens. 
While settings.json file is still being written, reading the file fails within the retries and then the IOException is thrown out.

**Comment by GangWang01** [comment]
Another new unstable issue appeared. Step Disable Azure CLI prompts failed randomly with error below.
```
/mnt/vss/_work/_temp/a65d2820-c2fc-4fca-b926-12c20e4dc317.sh: line 1: az: command not found
##[error]Bash exited with code '127'.
```
