### ISSUE TITLE
Unexpected Internal Software Issue (EX_SOFTWARE) An item with the same key has already been added. Key: -p:R

### ISSUE THREAD

**Issue by mkonijnenburg** [dotnet/templating#5588]
Updated VS, and got dotnet version 7.0.100.
Now my (unchanged) template fails, with stacktrace below. Cannot trace the -p:R to any parameters passed to dotnet new.

An item with the same key has already been added. Key: -p:R
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.CommandLine.Parsing.StringExtensions.ValidTokens(Command command)
   at System.CommandLine.Parsing.StringExtensions.Tokenize(IReadOnlyList`1 args, CommandLineConfiguration configuration, Boolean inferRootCommand)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ReparseForTemplate(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CliTemplateInfo template, Boolean validateDefaultLanguage)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ReparseForTemplate(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, IEnumerable`1 templatesToReparse, Boolean& languageOptionSpecified)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.GetTemplateCommand(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleTemplateInstantationAsync(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ExecuteIntAsync(InstantiateCommandArgs instantiateArgs, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, InvocationContext context)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.InvokeAsync(InvocationContext context)

For details on the exit code, refer to https://aka.ms/templating-exit-codes#70

**Comment by vlada-shubina** [comment]
@mkonijnenburg thank you for reaching out. Could you please provide more details on the template you are trying to run? 
If it's available publicly, could you please share the package name or template name?
If it's private, could you please share the set of symbols defined in the template and `dotnetcli.host.json` file. 
If it's possible, please share the output with debug enabled (add `--diagnostics` option).

**Comment by mkonijnenburg** [comment]
We are using a custom template. Below is the output with the  --diagnostics flag, there is not much more information. Next is the list of symbols in the template, I don't have a dotnetcli.host.json file with the template.

[2022-11-10 09:03:04.635] [Debug] [Template Engine] => [Execute]: Execute started
[2022-11-10 09:03:04.805] [Debug] [Template Engine] => [Execute]: Execute finished, took 172 ms
An item with the same key has already been added. Key: -p:R
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.CommandLine.Parsing.StringExtensions.ValidTokens(Command command)
   at System.CommandLine.Parsing.StringExtensions.Tokenize(IReadOnlyList`1 args, CommandLineConfiguration configuration, Boolean inferRootCommand)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ReparseForTemplate(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CliTemplateInfo template, Boolean validateDefaultLanguage)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ReparseForTemplate(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, IEnumerable`1 templatesToReparse, Boolean& languageOptionSpecified)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.GetTemplateCommand(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleTemplateInstantationAsync(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ExecuteIntAsync(InstantiateCommandArgs instantiateArgs, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, InvocationContext context)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.InvokeAsync(InvocationContext context)

For details on the exit code, refer to https://aka.ms/templating-exit-codes#70




	"symbols": { 
		"GuiType": {
			"type": "parameter", 
			"dataType": "choice",
			"defaultValue": "WinForms",
			"replaces": "__GuiType__",
			"fileRename": "__GuiType__",
			"description": "What is the type of the GUI?",
			"choices": [
				{
					"choice": "WinForms",
					"description": "Is the application WinForms?"
				},
				{
					"choice": "WPF",
					"description": "Is the application WPF?"
				}
			]
		},	
		"DataLogger": {
			"type": "parameter",
			"isRequired": true,
			"datatype": "bool",
			"defaultValue": "false",
			"description": "Include DataLogger"
		},
		"MeasurementEngine": {
			"type": "parameter",
			"isRequired": true,
			"datatype": "bool",
			"defaultValue": "false",
			"description": "Include Measurement Engine"
		},
		"ModeEngine": {
			"type": "parameter",
			"isRequired": true,
			"datatype": "bool",
			"defaultValue": "false",
			"description": "Include Mode Engine"
		},
		"Scripting": {
			"type": "parameter",
			"isRequired": true,
			"datatype": "bool",
			"defaultValue": "false",
			"description": "Include Scripting"
		},
		"GroupName": {
			"type": "parameter",
			"isRequired": true,
			"datatype": "string",
			"replaces": "__GroupName__",
			"description": "The name of the group."
		},
		"Organization": {
			"type": "parameter",
			"dataType": "choice",
			"defaultValue": "Amolf",
			"replaces": "__Organization__",
			"fileRename": "__Organization__",
			"description": "For which organization is this application developed.",
			"choices": [
				{
					"choice": "Amolf",
					"description": "AMOLF"
				},
				{
					"choice": "Arcnl",
					"description": "ARCNL"
				}
			]
		},
		"OrganizationUpper": {
			"type": "generated",
			"generator": "casing",
			"parameters": {
				"source": "Organization",
				"toLower": false
			},
			"replaces": "__OrganizationUpper__"
		},
		"ReplaceDebugSymbolWinForms": {
			"type": "parameter",
			"defaultValue": "",
			"replaces": ";__WinForms__"
		},
		"ReplaceDebugSymbolWPF": {
			"type": "parameter",
			"defaultValue": "",
			"replaces": ";__WPF__",
		},
		"ReplaceProjectNameWinforms": {
			"type": "parameter",
			"defaultValue": "",
			"replaces": "__WinForms__",
			"fileRename": "__WinForms__"
		},
		"ReplaceProjectNameWPF": {
			"type": "parameter",
			"defaultValue": "",
			"replaces": "__WPF__",
			"fileRename": "__WPF__"
		},
		"CopyrightYYYY": {
			"type": "generated",
			"generator": "now",
			"replaces": "__CopyrightYear__",
			"parameters": {
				"format": "yyyy"
			}
		},
		"CreateDateTime": {
			"type": "generated",
			"generator": "now",
			"parameters": {
				"format": "dd-MM-yyyy hh:mm:ss"
			},
			"replaces": "day/month/year"
		},
		"CreateDate": {
			"type": "generated",
			"generator": "now",
			"parameters": {
				"format": "yyyy-MM-dd"
			},
			"replaces": "__ymd__"
		},
		"TemplateUnComment": {
			"type": "parameter",
			"defaultValue": "", 
			"replaces": "//__TemplateUnComment__"
		},
		"TEMPLATE_AMOLF": {
			"type": "computed",
			"value": "(Organization == 'Amolf')"
		},
		"TEMPLATE_ARCNL": {
			"type": "computed",
			"value": "(Organization == 'Arcnl')"
		},
		"TEMPLATE_WINFORMS": {
			"type": "computed",
			"value": "(GuiType == 'WinForms')"
		},
		"TEMPLATE_WPF": {
			"type": "computed",
			"value": "(GuiType == 'WPF')"
		},
		"DATALOGGERINCLUDED": {
			"type": "computed",
			"value": "(DataLogger == 'true')"
		},	
		"MEASUREMENTENGINEINCLUDED": {
			"type": "computed",
			"value": "(MeasurementEngine == 'true')"
		},
		"MODEENGINEINCLUDED": {
			"type": "computed",
			"value": "(ModeEngine == 'true')"
		},
		"MODEENGINESUPPORTINCLUDED": {
			"type": "computed",
			"value": "(ModeEngine == 'true' && MeasurementEngine == 'true' && Scripting == 'true')"
		},
		"SCRIPTINGINCLUDED": {
			"type": "computed",
			"value": "(Scripting == 'true')"
		},
		"SIMPLEMEASUREMENT": {
			"type": "computed",
			"value": "(MeasurementEngine == 'false' && ModeEngine == 'false')"
		},
	},

**Comment by satyajit-behera** [comment]
I am also facing the same issue with update to visual studio. The same working template has stopped working with error: 
**An item with the same key has already been added. Key: -p:y**
refer to https://aka.ms/templating-exit-codes#70

**Comment by JanKrivanek** [comment]
Minimal repro:

`template.json`:
```json
{
  "$schema": "http://json.schemastore.org/template",
  "author": "dotnetnew",
  "classifications": [ "bug-repro" ], 
  "name": "Bug Repro",
  "identity": "bug-repro",         
  "groupIdentity":"bug-repro",
  "shortName": "bug-repro",                   
  "tags": { "type":"project" },
  "symbols": { 
	"Param1": {
		"type": "parameter",
	},
	"Param2": {
		"type": "parameter",
	},
	"Param3": {
		"type": "parameter",
	},
	"Param4": {
		"type": "parameter",
	}
  }
}
```

@mkonijnenburg, @satyajit-behera - thank you for reporting this issue and appology for the inconvenience caused. Issue is currently understood, fix is about to be submitted and it will be considered for the next servicing release.

In the meantime (before next servicing release) you have 2 options how **to workaround this issue:**

1. Edit the `template.json` - Rename the symbols in a way so that there are no more than 3 symbols with the same prefix
2. Add [`dotnetcli.host.json`](https://github.com/dotnet/templating/blob/main/docs/Reserved-Aliases.md)
  Add [`dotnetcli.host.json`](https://github.com/dotnet/templating/blob/main/docs/Reserved-Aliases.md) next to your `template.json` file and specify custom short aliases for your symbols, all turn them off alltogether.
  Sample  [`dotnetcli.host.json`](https://github.com/dotnet/templating/blob/main/docs/Reserved-Aliases.md) for the minimal repro above:
  ```json
  {
    "$schema": "http://json.schemastore.org/dotnetcli.host",
    "symbolInfo": {
      "Param1": {
        "shortName": ""
      },
  	"Param2": {
        "shortName": ""
      },
  	"Param3": {
        "shortName": ""
      },
  	"Param4": {
        "shortName": ""
      },
    }
  }
  ```

**Comment by JanKrivanek** [comment]
@mkonijnenburg  Please be aware that the symbols definitions you provided above can lead to another regression described here: https://github.com/dotnet/templating/issues/5600

That one issue won't prevent you from instantiation your template(s) in case all required options were provided. However it can lead to missleading error in case some required options are missing. To prevent that you can specify [default values](https://github.com/dotnet/templating/blob/main/docs/Reference-for-template.json.md#user-content-defaultvalue) for your symbols. Specifying `defaultValue` on required symbol will not stop the template engine from requiring it from the user on CLI - so it won't change the expected behavior.

**Comment by mkonijnenburg** [comment]
Thanks for the info and tip about the default value. I hope the fix will arrive shortly.
