### ISSUE TITLE
Unexpected Internal Software Issue (EX_SOFTWARE)

### ISSUE THREAD

**Issue by pantonis** [dotnet/templating#5972]
I'm trying to install a new template and I get the following error: 

````
Error: Failed to retrieve template packages from provider 'Global Settings'.
Details: Error reading JObject from JsonReader. Path '', line 0, position 0.
dotnet : Error reading JObject from JsonReader. Path '', line 0, position 0.
At line:1 char:1
+ dotnet new install .\
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error reading J... 0, position 0.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.TemplateEngine.JExtensions.ReadObject(IPhysicalFileSystem fileSystem, String path)
   at Microsoft.TemplateEngine.Edge.BuiltInManagedProvider.GlobalSettings.GetInstalledTemplatePackagesAsync(CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Edge.BuiltInManagedProvider.GlobalSettingsTemplatePackageProvider.InstallAsync(IEnumerable`1 installRequests, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.TemplatePackageCoordinator.EnterInstallFlowAsync(InstallCommandArgs args, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.Commands.InstallCommand.ExecuteAsync(InstallCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, 
InvocationContext context)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.InvokeAsync(InvocationContext context)

For details on the exit code, refer to https://aka.ms/templating-exit-codes#70
````

.NET SDK 7:

```
7.0.101 [C:\Program Files\dotnet\sdk]
7.0.102 [C:\Program Files\dotnet\sdk]
```

**Comment by YuliiaKovalova** [comment]
Hi @pantonis ,

It looks like a cache issue.
Could you check if the file C:\Users\%USERPROFILE%\.templateengine\packages.json isn't empty and wasn't corrupted?

**Comment by pantonis** [comment]
It was empty. I found out after 7 hours. Can't you just add a more friendly message?

**Comment by donJoseLuis** [comment]
@GangWang01 - to deliver this item, please sync with @YuliiaKovalova & agree on a proper message when cache is empty.

**Comment by pantonis** [comment]
@donJoseLuis Or when is corrupt. In general you need messages with details not just generic messages. We end up doing tooling troubleshooting instead of developing software

**Comment by YuliiaKovalova** [comment]
The message was added. 
Feel free to comment on the ticket if you have any other questions.
