### ISSUE TITLE
Unexpected Internal Software Issue (EX_SOFTWARE) - Creating blazor template

### ISSUE THREAD

**Issue by rsousacode** [dotnet/templating#5976]
Reproduction:

dotnet new blazorserver -o BlazorApp --no-https -f net7

```
Unable to cast object of type 'System.Boolean' to type 'System.String'.
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   at Microsoft.TemplateEngine.Cli.Commands.TemplateOptionResult.FromParseResult(TemplateOption option, ParseResult parseResult)
   at Microsoft.TemplateEngine.Cli.Commands.TemplateResult.FromParseResult(TemplateCommand templateCommand, ParseResult parseResult)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.CollectTemplateMatchInfo(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleNoTemplateFoundResult(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, IReporter reporter)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleTemplateInstantationAsync(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ExecuteIntAsync(InstantiateCommandArgs instantiateArgs, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, InvocationContext context)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.InvokeAsync(InvocationContext context)
   
   ``` 
   
  Platform:
  MacOS Arm 

dotnet --version
7.0.102

**Comment by YuliiaKovalova** [comment]
Hi @rsousacode,

Please try to run this as a workaround: 
`dotnet new blazorserver -o BlazorApp --no-https -f net7.0`

It is a known issue and it is addressed in 7.0.2 release.
See https://github.com/dotnet/templating/issues/5725 for getting more details.

Please let us know if this is acceptable - so that we can close the item. 

Best regards,
Yuliia Kovalova

**Comment by rsousacode** [comment]
Hi, @YuliiaKovalova,

I confirm that works. `dotnet new blazorserver -o BlazorApp --no-https` too.

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create it's using the command that can break, it didn't happen before I upgraded today my VS for Mac and the SDKs

**Comment by YuliiaKovalova** [comment]
Thank you for these details.
For version 6.0.xx this problem doesn't exist.

I close the ticket. If you have any concerns feel free to ping us again.
