### ISSUE TITLE
Investigate floating issue System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/templating#6275]
## Problem

On Linux machines, this issue is reported from time to time: 

```
Object name: 'GlobalSettings'.
   at Microsoft.TemplateEngine.Edge.BuiltInManagedProvider.GlobalSettings.GetInstalledTemplatePackagesAsync(CancellationToken cancellationToken) in /_/src/Microsoft.TemplateEngine.Edge/BuiltInManagedProvider/GlobalSettings.cs:line 75
   at Microsoft.TemplateEngine.Edge.UnitTests.GlobalSettingsTests.<>c__DisplayClass3_0.<<TestFileWatcher>b__0>d.MoveNext() in /_/test/Microsoft.TemplateEngine.Edge.UnitTests/GlobalSettingsTests.cs:line 54
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Aborted (core dumped)
=== COMMAND LINE ===
```

## Expected Fix

No issues with access to 'GlobalSettings'

**Comment by YuliiaKovalova** [comment]
close as no recent repro.
