### ISSUE TITLE
Unexpected Internal Software Issue (EX_SOFTWARE)

### ISSUE THREAD

**Issue by kyao-Frndz** [dotnet/templating#6620]
Unable to cast object of type 'System.Boolean' to type 'System.String'.
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   at Microsoft.TemplateEngine.Cli.Commands.TemplateOptionResult.FromParseResult(TemplateOption option, ParseResult parseResult)
   at Microsoft.TemplateEngine.Cli.Commands.TemplateResult.FromParseResult(TemplateCommand templateCommand, ParseResult parseResult)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.CollectTemplateMatchInfo(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleNoTemplateFoundResult(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, IReporter reporter)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleTemplateInstantationAsync(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ExecuteIntAsync(InstantiateCommandArgs instantiateArgs, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, InvocationContext context)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.InvokeAsync(InvocationContext context)

**Comment by YuliiaKovalova** [comment]
Hi @kyao-Frndz ,

Could you add your template.json file?
It can help us with the investigation and probably we will be able to suggest a workaround. 
Thank you!

**Comment by YuliiaKovalova** [comment]
Probably related to https://github.com/dotnet/templating/issues/6347

**Comment by donJoseLuis** [comment]
Indeed, similar to Probably related to https://github.com/dotnet/templating/issues/6347. That one was closed due to inactivity. The root-cause should be identified and fix, given this is the 2nd issue on that topic.

**Comment by YuliiaKovalova** [comment]
Close ticket due to lack of info for further investigation.
Feel free to reopen if provide the requested details.
