### ISSUE TITLE
Error `dotnet new blazorserver BlazorTestApp --no-https -f net7.0` on Windows 11 WSL Ubuntu

### ISSUE THREAD

**Issue by Eksno** [dotnet/templating#6732]
### Describe the bug
I was following [Blazor Tutorial](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create) and got to the create part where I ran into this error:
```
user@ubuntulinux:/mnt/c/path/to/project/folder$ dotnet new blazorserver BlazorTestApp --no-https -f net7.0
Unable to cast object of type 'System.Boolean' to type 'System.String'.
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   at Microsoft.TemplateEngine.Cli.Commands.TemplateOptionResult.FromParseResult(TemplateOption option, ParseResult parseResult)
   at Microsoft.TemplateEngine.Cli.Commands.TemplateResult.FromParseResult(TemplateCommand templateCommand, ParseResult parseResult)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.CollectTemplateMatchInfo(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleNoTemplateFoundResult(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, IReporter reporter)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleTemplateInstantationAsync(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ExecuteIntAsync(InstantiateCommandArgs instantiateArgs, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, InvocationContext context)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.InvokeAsync(InvocationContext context)

For details on the exit code, refer to https://aka.ms/templating-exit-codes#70
```

### To Reproduce

1. Install WSL with `wsl --install`
2. Install Ubuntu in WSL with `wsl --install -d Ubuntu`
3. Open the WSL terminal and install .NET SDK 7.0. [DotNET Core Install Ubuntu 22.04 LTS](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204)
4. Run `dotnet new blazorserver BlazorTestApp --no-https -f net7.0` [Blazor Tutorial Create](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create)

### Further technical details
```
.NET SDK:
 Version:   7.0.107
 Commit:    bf72c06963

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.107/

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  7.0.107 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.7 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
- WSL2 Ubuntu Terminal

#### Neofetch
OS: Ubuntu 22.04.2 LTS on Windows 11 x86_64
Kernel: 5.15.90.1-microsoft-standard-WSL2
Uptime: 32 mins
Packages: 544 (dpkg)
Shell: bash 5.1.16
Terminal: Relay(2113)
CPU: 11th Gen Intel i7-1185G7 (8) @ 2.995GHz
GPU: 6bca:00:00.0 Microsoft Corporation Device 008e
Memory: 328MiB / 15849MiB

**Comment by YuliiaKovalova** [comment]
@GangWang01 please take a look.
Probably there is a misuse of the command.

**Comment by YuliiaKovalova** [comment]
@Eksno , could you try to run the command: 
`dotnet new blazorserver -n "BlazorTestApp" --no-https -f net7.0`

It looks like you have invalid params in your example.

**Comment by Eksno** [comment]
@YuliiaKovalova, ran the command. It worked successfully

```
$ dotnet new blazorserver -n "BlazorTestApp2" --no-https -f net7.0
The template "Blazor Server App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/7.0-third-party-notices for details.

Processing post-creation actions...
Restoring /mnt/c/home/local/vcs/testing/BlazorTestApp2/BlazorTestApp2.csproj:
  Determining projects to restore...
  Restored /mnt/c/home/local/vcs/testing/BlazorTestApp2/BlazorTestApp2.csproj (in 72 ms).
Restore succeeded.
```

However the previous command that did not work in WSL did work in native Powershell. It is also the one that is recommended [here](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create).

**Comment by YuliiaKovalova** [comment]
> @YuliiaKovalova, ran the command. It worked successfully
> 
> ```
> $ dotnet new blazorserver -n "BlazorTestApp2" --no-https -f net7.0
> The template "Blazor Server App" was created successfully.
> This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/7.0-third-party-notices for details.
> 
> Processing post-creation actions...
> Restoring /mnt/c/home/local/vcs/testing/BlazorTestApp2/BlazorTestApp2.csproj:
>   Determining projects to restore...
>   Restored /mnt/c/home/local/vcs/testing/BlazorTestApp2/BlazorTestApp2.csproj (in 72 ms).
> Restore succeeded.
> ```
> 
> The previous command that did not work in WSL did work in native PowerShell. It is also the one that is recommended [here](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create?initial-os=linux).

In the tutorial the command looks a bit different
`dotnet new blazorserver -o BlazorApp --no-https -f net7.0`.
`-o` is missed in your ticket.
