### ISSUE TITLE
Deepin15.2    dotnet restore failure

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#776]
_From @Hareis on May 10, 2017 13:37_

## Steps to reproduce
按照官方的教程安装的

## Environment data
`dotnet --info` output:

areis@hareis-pc:/media/hareis/娱乐/CSharpSolution/myBlog$ dotnet restore
段错误
hareis@hareis-pc:/media/hareis/娱乐/CSharpSolution/myBlog$   Restoring packages for /media/hareis/娱乐/CSharpSolution/myBlog/myBlog.common/myBlog.common.csproj...
  Restoring packages for /media/hareis/娱乐/CSharpSolution/myBlog/myBlog.dataAccess/myBlog.dataAccess.csproj...
  Restoring packages for /media/hareis/娱乐/CSharpSolution/myBlog/myBlog.model/myBlog.model.csproj...
  Restoring packages for /media/hareis/娱乐/CSharpSolution/myBlog/myBlog.service/myBlog.service.csproj...

hareis@hareis-pc:/media/hareis/娱乐/CSharpSolution/myBlog$

dotnet new console -o hwapp
Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.EnsureLoaded()
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.GetTemplates(HashSet`1 templates)
   at Microsoft.TemplateEngine.Edge.Template.TemplateCreator.List(Boolean exactMatchesOnly, Func`3[] filters)
   at Microsoft.TemplateEngine.Cli.New3Command.PerformCoreTemplateQueryAsync()
   at Microsoft.TemplateEngine.Cli.New3Command.<EnterTemplateManipulationFlowAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__66.MoveNext()

_Copied from original issue: dotnet/cli#6564_

**Comment by mlorbetske** [comment]
Please run `dotnet new --debug:reinit`, this should cause the configuration to get rebuilt. The next time `dotnet new` runs, things should be back to normal.

**Comment by Hareis** [comment]
@mlorbetske  按照你说的做了，但是这个错误，怀疑是这个deepin的底层去掉了某些依赖，导致的问题

**Comment by mlorbetske** [comment]
Sorry, I'm not sure I understand. Did running that command fix the issue?

**Comment by Hareis** [comment]
@mlorbetske  没有的

**Comment by mlorbetske** [comment]
@seancpeters can you take a look?

**Comment by mlorbetske** [comment]
@Hareis if you do `dotnet new console --debug:ephemeral-hive` does it work?

**Comment by Hareis** [comment]
@mlorbetske  没有截图 那是家里的电脑

**Comment by seancpeters** [comment]
@Hareis 
Please run this command and copy the output here:
`dotnet --info`

Also, please run this command and copy the output here:
`dotnet new --debug:showconfig`

**Comment by mlorbetske** [comment]
Are you still running in to this?

**Comment by mlorbetske** [comment]
Closing this as we haven't gotten the information needed to continue to investigate. Please re-open if you're still running in to this and are able to provide the additional information.
