### ISSUE TITLE
.NET Framework test class clean-up failure

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/templating#8072]
@akoeplinger and I noticed in https://github.com/dotnet/templating/pull/8065 that at least on .NET Framework tests  sometimes fail:

> ##[error]XUnit(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Tests failed: D:\a\_work\1\s\artifacts\TestResults\Release\Microsoft.TemplateEngine.Edge.UnitTests_net48_x64.html [net48|x64]

**Comment by ViktorHofer** [comment]
```
     [Test Class Cleanup Failure (Microsoft.TemplateEngine.Edge.UnitTests.TemplatePackageManagerTests)] System.UnauthorizedAccessException
      System.UnauthorizedAccessException : Access to the path 'C:\Users\cloudtest\AppData\Local\Temp\TemplateEngine.Tests\89c054c5-9d7b-41db-99b7-253514b934a5\.templateengine' is denied.
      Stack Trace:
           at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
           at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
        /_/test/Microsoft.TemplateEngine.TestHelper/EnvironmentSettingsHelper.cs(84,0): at Microsoft.TemplateEngine.TestHelper.EnvironmentSettingsHelper.<>c.<Dispose>b__5_0(String f)
           at System.Collections.Generic.List`1.ForEach(Action`1 action)
        /_/test/Microsoft.TemplateEngine.TestHelper/EnvironmentSettingsHelper.cs(73,0): at Microsoft.TemplateEngine.TestHelper.EnvironmentSettingsHelper.Dispose()
  Finished:    Microsoft.TemplateEngine.Edge.UnitTests
=== TEST EXECUTION SUMMARY ===
   Microsoft.TemplateEngine.Edge.UnitTests  Total: 268, Errors: 1, Failed: 0, Skipped: 0, Time: 10.417s
```

**Comment by akoeplinger** [comment]
Fixed by https://github.com/dotnet/templating/pull/8094
